### ISSUE TITLE
Migrating to Class Based

### ISSUE THREAD

**Issue by Somokai** [Somokai/WhatShouldWePlay#10]
I think, given the amount of information we want to add to individual aspects of this tool, it may be a good idea to swap over to a class based approach. Alternatively, if we move to user-based files, this may not be necessary depending on the implementation. 

My primary concern for a class based approach is performance, classes are generally slower to use than other methods.

**Comment by Javagedes** [comment]
I have an implementation of this already, just needed the token to test before I pushed the PR.
