### ISSUE TITLE
Is a guild file necessary?

### ISSUE THREAD

**Issue by Javagedes** [Somokai/WhatShouldWePlay#5]
Personally, I don't think having a guild file is necessary, that locks it down too much. I think the best option is for each user to have their own file that is compatible across all guilds (servers). If you really want to add the ability for a user to have different games on different servers, then maybe we can subdivide the user's json file.

Idea for the user json file as it stands
```json
{
  "games": ["game1", "game2"]
}
```

Idea for the user json file if you really want to separate by guilds

```json
{
  "Server1": {"games": ["game1", "game2"]},
  "Server2": {"games": ["game1", "game3"]}
}
```

**Comment by Somokai** [comment]
In general I only have two concerns about moving over to a user based system. The first is that we may want to keep statistics on games selected, time played, etc. This could be a separate file anyway though so it's not a big deal. The second would be performance in searching if there are a lot of people using the bot, but honestly probably not an issue. 

I'm fine moving to user based files overall, but I'm not sure whether I want subdivision. I can see a use case where someone only likes to play a given game in specific server, but I don't know how important that is to consider.
