### ISSUE TITLE
Blacklisting

### ISSUE THREAD

**Issue by Somokai** [Somokai/WhatShouldWePlay#6]
We currently have a feature that allows the bot to scrape data from what people are playing and automatically adding that game to a list. We need a way to keep track of a blacklist where if a game is "blacklisted" it's no longer automatically added.

**Comment by Javagedes** [comment]
Agree! Easy enough to add into their user profile json file.
```json
{
  "games" : [],
  "blacklist" : [],
  "Statistics" : {}
}
```

**Comment by Javagedes** [comment]
#12 changed data managerment to user record based. The user record has a blacklist as mentioned above. I did not add functionality to actually blacklist games though. Will do that if the PR is approved.

**Comment by Javagedes** [comment]
I'm not sure the best way to do this without having a 2 word command. Some of the options I can think of are:

```
$blacklist add <game>
$blacklist remove <game>

$blacklist <game>
$whitelist <game>
```

Any preferences or other ideas?

**Comment by Somokai** [comment]
blacklist and whitelist seem better overall, less typing. By default we are thinking all games are "whitelisted" correct? Just in the general game pool.

**Comment by Javagedes** [comment]
Yes, all games are whitelisted and can be added by default. Using the keyword whitelist is to just undo the blacklist command/ remove a game from the blacklist. It doesn't *exactly* match what whitelisting does in the real world.

**Comment by Somokai** [comment]
Yeah, seems unblacklist is a thing that exists also. So we could also use that.

**Comment by Javagedes** [comment]
unblacklist is fine by me
